name: Deploy Multiple Proxies

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-apigee:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v3

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Get Apigee Bearer Token
        id: token
        run: echo "token=$(gcloud auth print-access-token)" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_org_name: "my-existing-org"   # or from secrets
          TF_VAR_env_name: "test"
          TF_VAR_apigee_bearer_token: ${{ steps.token.outputs.token }}
        run: terraform apply -auto-approve
